import { useParams } from '@solidjs/router';
import { Link } from './Button';

export const DropZone = () => {
  const params = useParams();

  return (
    <div class="p-4 border-2 border-dashed border-foreground rounded-lg min-h-96 flex items-center justify-center">
      <div class="text-foreground text-lg">
        {params.id && (
          <div class="flex flex-col gap-8 gap-4 items-center justify-center">
            <h2 class="text-2xl">Drop or paste this file here:</h2>
            <p>
              <code>venz-drop-{params.id}.json</code>
            </p>
            <p>
              <Link href={`/config/${params.id}`}>← back to configuration</Link>
            </p>
          </div>
        )}
        {!params.id && (
          <div class="flex flex-col gap-8">
            <h2 class="text-3xl">Create chart from numbers</h2>
            <h3 class="text-2xl">Drag & drop or copy-paste a file or text:</h3>
            <ul class="list-disc ml-4">
              <li>Plain text numbers separated by newline, space, comma or semicolon (= one data series)</li>
              <li>Multiple numbers on a single line represent one data series</li>
              <li>JSON array containing numbers or arrays of numbers</li>
              <li>
                JSON generated by <code>hyperfine --export-json</code> (<code>--parameter-list</code> supported)
              </li>
            </ul>
            <p>Add data series by dropping/pasting data again</p>
          </div>
        )}
      </div>
    </div>
  );
};
